import Testing
@testable import RecallyxCore

@Suite("PrivacyFilter")
struct PrivacyFilterTests {
    // The string type-identifiers a pasteboard exposes (NSPasteboard.PasteboardType.rawValue).
    private let stringType = "public.utf8-plain-text"
    private let plain: [String] = ["public.utf8-plain-text"]
    private var concealed: [String] { [stringType, PrivacyFilter.concealedType] }
    private var transient: [String] { [stringType, PrivacyFilter.transientType] }
    private var autoGenerated: [String] { [stringType, PrivacyFilter.autoGeneratedType] }

    @Test func plainText_alwaysCaptured() {
        #expect(PrivacyFilter.shouldCapture(types: plain, captureSensitive: false))
        #expect(PrivacyFilter.shouldCapture(types: plain, captureSensitive: true))
    }

    @Test func concealed_skippedWhenSensitiveOff() {
        #expect(!PrivacyFilter.shouldCapture(types: concealed, captureSensitive: false))
    }

    @Test func concealed_capturedWhenSensitiveOn() {
        #expect(PrivacyFilter.shouldCapture(types: concealed, captureSensitive: true))
    }

    @Test func transient_skippedWhenSensitiveOff() {
        #expect(!PrivacyFilter.shouldCapture(types: transient, captureSensitive: false))
    }

    @Test func autoGenerated_skippedWhenSensitiveOff() {
        #expect(!PrivacyFilter.shouldCapture(types: autoGenerated, captureSensitive: false))
    }

    @Test func emptyOrWhitespaceText_isSkippable() {
        #expect(PrivacyFilter.isSkippableText(""))
        #expect(PrivacyFilter.isSkippableText("   \n\t "))
        #expect(!PrivacyFilter.isSkippableText("hello"))
        #expect(!PrivacyFilter.isSkippableText("  hi  "))
    }
}
