import AppKit

/// Decides whether a pasteboard change should be captured. Pure logic so it can
/// be unit-tested without a live `NSPasteboard`.
enum PrivacyFilter {
    /// Pasteboard hint types that password managers / transient producers set to
    /// ask clipboard managers not to record their contents.
    /// See http://nspasteboard.org.
    static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    /// When `captureSensitive` is off, a pasteboard carrying any concealed /
    /// transient / auto-generated hint is skipped.
    static func shouldCapture(types: [NSPasteboard.PasteboardType], captureSensitive: Bool) -> Bool {
        if captureSensitive { return true }
        let hinted: Set<NSPasteboard.PasteboardType> = [concealedType, transientType, autoGeneratedType]
        return types.allSatisfy { !hinted.contains($0) }
    }

    /// Empty / whitespace-only text carries nothing worth storing.
    static func isSkippableText(_ s: String) -> Bool {
        s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}
