import Foundation

/// Decides whether a pasteboard change should be captured. Pure logic operating
/// on plain type-identifier strings (UTIs / pasteboard type raw values) so it
/// stays platform-free and unit-testable without a live `NSPasteboard`. The app
/// passes the pasteboard's type identifiers (`NSPasteboard.PasteboardType.rawValue`).
public enum PrivacyFilter {
    /// Pasteboard hint type identifiers that password managers / transient
    /// producers set to ask clipboard managers not to record their contents.
    /// See http://nspasteboard.org.
    public static let concealedType = "org.nspasteboard.ConcealedType"
    public static let transientType = "org.nspasteboard.TransientType"
    public static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

    /// When `captureSensitive` is off, a pasteboard carrying any concealed /
    /// transient / auto-generated hint is skipped.
    public static func shouldCapture(types: [String], captureSensitive: Bool) -> Bool {
        if captureSensitive { return true }
        let hinted: Set<String> = [concealedType, transientType, autoGeneratedType]
        return types.allSatisfy { !hinted.contains($0) }
    }

    /// Empty / whitespace-only text carries nothing worth storing.
    public static func isSkippableText(_ s: String) -> Bool {
        s.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}
